name: CI with Docker, Pytest

on:
  push:
    branches:
      - master
      - feat-ci-cd
  pull_request:
    branches:
      - master
      - feat-ci-cd

permissions:
  pull-requests: write
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker
        run: docker build --no-cache -t ci-cd-demo .

      - name: Run tests with report
        run: |
          docker run --rm ci-cd-demo \
          pytest --alluredir=./allure-results tests/

      - name: Generate Allure test report
        uses: andgineer/allure-report@v3.6
        id: allure-report
        if: always()
        with:
          allure-results: allure-results
          website: gh-pages-dir
          reports-site-path: builds/tests

      - name: Publish Allure test report
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ always() && (steps.allure-report.outcome == 'success') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ steps.allure-report.outputs.reports-site }}
          destination_dir: ${{ steps.allure-report.outputs.reports-site-path }}
