name: CI with Docker, Pytest

on:
  push:
    branches:
      - master
      - feat-ci-cd
  pull_request:
    branches:
      - master
      - feat-ci-cd

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker
        run: docker build --no-cache -t ci-cd-demo .

      - name: Run tests
        run: docker run --rm ci-cd-demo pytest

